### ISSUE TITLE
Crash ao passar na tarja

### ISSUE THREAD

**Issue by CharlesNascimento** [stone-payments/sdk-ios#22]
Olá. Estou tendo um problema ao passar alguns cartões na tarja. Os pinpads utilizados foram uma MOBIPIN 10 e uma PAX D-180. Os cartões são variados, não notei nenhum padrão. O motivo do crash é o seguinte:

`Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString characterAtIndex:]: Index 1 out of bounds; string length 1'`

Aguardo resposta, obrigado.

**Comment by filpgame** [comment]
Corrigido na [v2.5.3](https://github.com/stone-payments/sdk-ios/releases/tag/2.5.3).
Obrigado pelo feedback!
